apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: ccr.ccs.tencentyun.com/ts-go/user:1.0
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: MYSQL_DSN
              value:
      imagePullSecrets:
        - name: qcloudregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8090